# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Frederick Law
# email: Law@cims.nyu.edu
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username:
github_username:  fredglaw
include: ["_pages"]

# Build settings
# theme: minima
# theme: minimal-mistakes-jekyll
#theme: panthera-jekyll
#theme: plainwhite
#remote_theme: christianezeani/panthera-jekyll
plugins:
  # - jekyll-feed
  - jekyll-include-cache

# minima:
#   skin: dark

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# minimal-mistakes-jekyll:
  # skin: sunrise

# header_pages: 
# - about.markdown

minimal_mistakes_skin: "dirt"

author: email link

author:
  name: "Frederick Law"
  avatar: "/assets/images/me.jpg"
  bio: "Applied Mathematician" # Note: Markdown is allowed
  location: "New York City, USA"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/fredglaw/"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/mmistakes"


sidebar:
  - title: "Title"
    image: http://placehold.it/350x250
    image_alt: "image"
    text: "Some text here."
  - title: "Another Title"
    text: "More text here."


defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true